dist: trusty
sudo: required

language: node_js
node_js:
  - '4.6'

addons:
  apt:
    packages:
      - build-essential
      - uuid-dev

script:
  - npm test
  - npm run lint
  - npm run cover

after_success:
  - npm run doc
  - npm run report

deploy:
  - provider: s3
    on:
      branch: master
    access_key_id: AKIAIY5ZQMX6KC4737JQ
    secret_access_key:
      secure: FmSyFyi3xgTH4zpUemho0oqtIuWj2y/9RhgcwFEFQHtxy5Ntj2bxLXoOlJgjcV4PZMTTMQ7UY8+FAcs5p8adxaO/ozfZuYiEqOMjuTvwGLLz5y/+778VrrO1hafd2YRYAriYf2fb1Y99+VDA/oZTUxNbhzPIOH/ixYFLA3AXbVPRM0gAJ4TJ8gTJbvnZ30IahmF4KfgPLmR2odagY2VM7yAt8GmSt8dZEh7FPrelmXwFoqbMxgnIC56BwW4ZInkvY1Z5MZCvW6etOUylcBSYTzzfRYmP2LutF9gkERuTUOMRKsEtOcxEFRTLl0PW7swDwkyOH8fFHsigTCHp+MJCUvPSot330u+mlLvtTU6ExwS1pmR8VaskYa0JIu7xpv2lWI1Ch19PwtJsQOMXNkpBmEbBiWGklmz4/MmYhg7E4ldUWTbZUiDjDdKgTLXz8RnsLhLmWnfmG+7uPaPzFZebY5FCbi64v4mOQW09sFAvqCrbBXB7MCbzsGlLTMaixmx8VlplDZdG5QOv73Hzr4UXSe6COz7vIddJ2++2qdT/41esSIgeqOKQtL9p6zOz9MAFiAdBOS1MSsK8hAHiVZmwRGXlf3Uo7UiyzJH/2p53ApJboJb63I6y178v6dRiTmj1c1iAEWEM+JrkfHmgTT6bTRJptrvQQ0zOYy3bCLU4Ux8=
    bucket: docs.manero.io
    acl: public_read
    skip_cleanup: true
    local_dir: docs/jsdoc
    upload-dir: jsdoc/jmanero/reftact
