dist: trusty
sudo: required

language: node_js
node_js:
  - '4.6'

addons:
  apt:
    packages:
      - build-essential
      - uuid-dev

script:
  - npm test
  - npm run lint
  - npm run cover

after_success:
  - npm run doc
  - npm run report

deploy:
  - provider: s3
    on:
      branch: master
    access_key_id: AKIAJZKIRSVRUSZYNIBA
    secret_access_key:
      secure: BkwWnFyUSq3E3IVXs+Vf4a0+LoeMftuqQEw9JvYtJ94r2mpuSznKiC2gWwhOpfscAZiZZkvj/Wule5Xq4mTHXjbChSPcD09lMRwzlWwOlfE9A6Pwry9Ko8JfEYJCk2IS227U+uEQKY+hyEqAztEd0qQaAVz53Nn5sMEpgjHv9kiHqod013uwXYhbhUCLgoY86XtOBFf8aZW74Ahh70UjEIHGU4ePM4GXrUEAvYtlgPlasMcG4mxIldVfnNgJE4ihxdCSVJd3Rnc6gj25TkJOUGIPt8QXIw284n1biQCkm8DvAfSQTfacVyqDdyiM442KZ8ldk2irili8ZPHJGuVYXcApGOkhyrRX4wDnMtJ0q1PXxE9x4zZ3w23pso5Ea5+fsvfQBeEAtrUJndApGZemaio2vUci74jnEzm3nlH6gome/sQWDim6OR5hDYTVqgYLTBuz9k7Ck///sMibyh9dgwu8Bvf6w6Mc48QFCNPTVH06sji7A65Y1T92WLoR8zoxMOA08dAV/EaNPbYwHjN7E4s+KaxBmolEqxfNNgRnwigtWth/Q7DxdmCmrz/wk+zksn3ZCpReRkVwCU+jRgBAKXNNOtOBPVOc8WsDdVoXTfztOFikYL/TRnlpT4hCxnpCLK8cWNt5oLMvxxagsgI9GkhTAjqnS39W5GSFG1nUl2w=
    bucket: docs.manero.io
    acl: public_read
    skip_cleanup: true
    local_dir: docs/jsdoc
    upload-dir: jsdoc/jmanero/reftact
